-- Converted from SQLite dump_utf8.sql to PostgreSQL
BEGIN;

-- users
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

INSERT INTO users (id, username, password) VALUES
(4,'Sofia','$2b$10$X0omVElGN5PlEbVevb7J3u/pfpCHAOuh/96NW.VOeUpS6hd.LjSOq');

-- tabs
CREATE TABLE IF NOT EXISTS tabs (
  id SERIAL PRIMARY KEY,
  name TEXT,
  user_id INTEGER REFERENCES users(id)
);

INSERT INTO tabs (id, name, user_id) VALUES
(1,'Thực đơn sống qua ngày',4),
(3,'Thực đơn giảm cân',4);

-- blocks
CREATE TABLE IF NOT EXISTS blocks (
  id SERIAL PRIMARY KEY,
  tab_id INTEGER REFERENCES tabs(id),
  user_id INTEGER REFERENCES users(id),
  day_name TEXT,
  breakfast TEXT,
  lunch TEXT,
  dinner TEXT
);

INSERT INTO blocks (id, tab_id, user_id, day_name, breakfast, lunch, dinner) VALUES
(5,1,4,'Thứ Hai','sinh tố: 1 ly','Bò sốt rượu vang: 500g','Trứng cá muối: 50g, Cơm gà: 1 đĩa'),
(6,1,4,'Thứ Ba','Xôi gà: 100g','Cơm: 100g, cá: 1 con', E'Cơm: 100g \n, thịt bò: 50g'),
(7,1,4,'Thứ Tư','Bánh mì: 1 ổ','Cơm: 1 tô, cá: 2 con','Cơm: 1 tô, gà: 200g'),
(8,3,4,'Ngày 1','Trứng ốp la: 2 quả, Bánh mì: 1 ổ','Cơm: 1 chén, rau xanh: 50g, thịt luộc: 100g','Phở: 1 tô');

-- chats
CREATE TABLE IF NOT EXISTS chats (
  id SERIAL PRIMARY KEY,
  thread_id INTEGER REFERENCES threads(id),
  user_id INTEGER REFERENCES users(id),
  content TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  image_path TEXT
);

INSERT INTO chats (id, thread_id, user_id, content, role, image_path) VALUES
(1,1,4,'What is your name? Can you give me an easy diet to lose weight?','user',NULL),
(2,1,4,'What is your name? Can you give me an easy diet to lose weight?','user',NULL),
(3,1,4,'What is your name? Can you give me an easy diet to lose weight?','user',NULL),
(4,1,4, E'My name is Fit-Chef! I\u2019d be happy to help you with an easy diet plan for weight loss. Here\'s a simple, balanced approach that focuses on whole foods and portion control:\n\n### Easy Weight Loss Diet Plan\n\n#### Breakfast\n- **Option 1:** Greek yogurt with a handful of berries and a sprinkle of nuts.\n- **Option 2:** Oatmeal topped with sliced banana and a tablespoon of almond butter.\n\n#### Snack\n- **Option:** A small apple or a banana with a tablespoon of natural peanut butter.\n\n#### Lunch\n- **Option 1:** Grilled chicken salad with mixed greens, cherry tomatoes, cucumber, and a vinaigrette dressing.\n- **Option 2:** Quinoa bowl with black beans, corn, diced bell peppers, and avocado.\n\n#### Snack\n- **Option:** Carrot sticks or cucumber slices with hummus.\n\n#### Dinner\n- **Option 1:** Baked salmon with steamed broccoli and sweet potato.\n- **Option 2:** Stir-fried tofu with mixed vegetables (like bell peppers, broccoli, and snap peas) over brown rice.\n\n#### Hydration\n- Drink plenty of water throughout the day (aim for at least 8 cups).\n- Herbal teas or infused water with lemon, cucumber, or mint can also be refreshing.\n\n### Tips for Success\n- **Portion Control:** Be mindful of your serving sizes, even with healthy foods.\n- **Limit Processed Foods:** Try to minimize added sugars, refined carbs, and processed snacks.\n- **Physical Activity:** Incorporate regular exercise, such as walking, cycling, or strength training, for additional benefits.\n- **Listen to Your Body:** Pay attention to hunger cues and eat when you\'re hungry, stopping when you\'re satisfied.\n\nAlways consult with a healthcare professional or a registered dietitian before starting any new diet plan, especially if you have specific health conditions or concerns. Good luck on your weight loss journey!','assistant',NULL),
(5,1,4,'Can I eat sweet sometimes?','user',NULL),
(6,1,4, E'Absolutely! Enjoying sweets in moderation is perfectly fine and can be part of a balanced diet. Here are some tips for incorporating sweets into your diet without derailing your weight loss goals:\n\n### Tips for Eating Sweets in Moderation\n\n1. **Portion Control:** Opt for smaller portions of your favorite sweets. Instead of a large dessert, try a small piece of chocolate or a few bites of cake.\n\n2. **Choose Healthier Options:** Look for healthier alternatives, such as dark chocolate (70% cocoa or higher), fruit-based desserts, or yogurt with a drizzle of honey.\n\n3. **Savor the Flavor:** Take your time to enjoy your sweet treat. Eating slowly can help you feel satisfied with less.\n\n4. **Balance with Healthy Foods:** If you plan to have a sweet treat, balance it out by eating a healthy meal or snack beforehand to help mitigate cravings.\n\n5. **Limit Frequency:** Designate a specific day or occasion for enjoying sweets, such as a weekend treat, to help you stay on track during the week.\n\n6. **Homemade Treats:** Consider making your own desserts with healthier ingredients, such as using whole grains, reducing sugar, or incorporating fruits and nuts.\n\n### Example Sweet Treats\n- **Fruit Salad:** Fresh fruit mixed with a sprinkle of cinnamon or a dollop of yogurt.\n- **Dark Chocolate-Covered Almonds:** A satisfying combination of healthy fats and a sweet touch.\n- **Banana Ice Cream:** Frozen bananas blended until creamy for a simple, healthy dessert.\n\nRemember, moderation is key! Enjoying sweets occasionally can help satisfy your cravings and make your diet more enjoyable, which can lead to long-term success.','assistant',NULL),
(7,1,4,'What food should I be refrain of consumming?','user',NULL),
(8,1,4, E'To support your weight loss goals and overall health, it\'s a good idea to limit or refrain from certain foods that can be high in calories, added sugars, unhealthy fats, and low in nutrients. Here\'s a list of foods you might want to minimize:\n\n### Foods to Refrain From\n\n1. **Sugary Drinks:**\n   - Sodas, sweetened teas, and energy drinks are high in sugar and calories but provide little to no nutritional value.\n\n2. **Processed Snacks:**\n   - Chips, cookies, and packaged snack foods often contain unhealthy fats, added sugars, and preservatives.\n\n3. **Refined Carbohydrates:**\n   - White bread, pastries, and many baked goods can lead to blood sugar spikes and are often low in fiber.\n\n4. **Fast Food:**\n   - Most fast-food items are high in calories, unhealthy fats, and sodium, making them less suitable for a weight loss diet.\n\n5. **Candy and Sweets:**\n   - Candies, chocolates, and desserts that contain high amounts of sugar can contribute to excess calorie intake.\n\n6. **High-Calorie Coffee Drinks:**\n   - Specialty coffee drinks with whipped cream, flavored syrups, and added sugars can be very calorie-dense.\n\n7. **Ice Cream and High-Fat Desserts:**\n   - While it\'s okay to indulge occasionally, these desserts can be high in sugar and fat.\n\n8. **Processed Meats:**\n   - Items like sausages, hot dogs, and deli meats can be high in sodium and preservatives.\n\n9. **Fried Foods:**\n   - Foods that are deep-fried can be high in unhealthy fats and calories.\n\n10. **High-Sugar Breakfast Cereals:**\n    - Many cereals marketed as "healthy" can be high in added sugars. Look for whole grain options with minimal sugar.\n\n### Tips for Making Better Choices\n- **Read Labels:** Check for added sugars, unhealthy fats (like trans fats), and sodium in packaged foods.\n- **Focus on Whole Foods:** Aim for whole, minimally processed foods like fruits, vegetables, whole grains, lean proteins, and healthy fats.\n- **Plan Ahead:** Prepare meals and snacks in advance to avoid reaching for unhealthy options when you\'re hungry.\n\nRemember, it\'s not about complete restriction but rather about making mindful choices that align with your health and weight loss goals. Occasional treats are fine as long as they fit into your overall balanced diet!','assistant',NULL),
(9,1,4,'What excercise should I practice?','user',NULL),
(10,1,4, E'Incorporating regular exercise into your routine can significantly enhance your weight loss efforts and overall health. Here are some effective types of exercises you can practice, along with suggestions for how to include them in your week:\n\n### Types of Exercises\n\n1. **Cardiovascular (Aerobic) Exercise:**\n   - **Examples:** Walking, jogging, running, cycling, swimming, dancing, or group fitness classes.\n   - **Recommendation:** Aim for at least 150 minutes of moderate-intensity aerobic exercise per week (e.g., brisk walking) or 75 minutes of vigorous-intensity exercise (e.g., running).\n\n2. **Strength Training:**\n   - **Examples:** Weight lifting, bodyweight exercises (push-ups, squats, lunges), resistance band workouts.\n   - **Recommendation:** Include strength training exercises at least 2-3 times per week. Focus on major muscle groups (legs, back, chest, arms).\n\n3. **Flexibility and Stretching:**\n   - **Examples:** Yoga, Pilates, static stretching, or dynamic stretches.\n   - **Recommendation:** Incorporate flexibility exercises into your routine at least 2-3 times per week to improve range of motion and reduce injury risk.\n\n4. **High-Intensity Interval Training (HIIT):**\n   - **Examples:** Short bursts of intense exercise followed by rest or low-intensity activity (e.g., sprinting for 30 seconds, followed by walking for 1 minute).\n   - **Recommendation:** Include HIIT workouts 1-2 times a week. These can be time-efficient and effective for burning calories.\n\n5. **Functional Training:**\n   - **Examples:** Exercises that mimic everyday activities, such as squats, deadlifts, and kettlebell swings.\n   - **Recommendation:** Incorporate functional exercises into your strength training routine to improve overall strength and coordination.\n\n### Sample Weekly Exercise Plan\n\n- **Monday:** 30 minutes of brisk walking + 20 minutes of strength training (upper body)\n- **Tuesday:** 20 minutes of HIIT workout\n- **Wednesday:** 30 minutes of cycling or swimming\n- **Thursday:** 30 minutes of strength training (lower body) + 15 minutes of stretching\n- **Friday:** 30 minutes of jogging or dancing\n- **Saturday:** Rest day or light activity (like a leisurely walk)\n- **Sunday:** 30 minutes of yoga or Pilates for flexibility\n\n### Tips for Success\n- **Find Activities You Enjoy:** Choose exercises that you find fun and engaging to help you stay consistent.\n- **Set Realistic Goals:** Start with achievable goals and gradually increase the intensity and duration of your workouts.\n- **Stay Consistent:** Aim for regular exercise throughout the week rather than sporadic intense sessions.\n- **Listen to Your Body:** Rest when needed, and don\'t push through pain or discomfort.\n\nConsult with a healthcare professional or a certified trainer before starting a new exercise program, especially if you have any pre-existing health conditions or concerns. Enjoy your fitness journey!','assistant',NULL),
(11,1,4,'What types of chocolate can I eat','user',NULL),
(12,1,4, E'When it comes to enjoying chocolate while maintaining a balanced diet, the type of chocolate you choose can make a significant difference. Here are some types of chocolate that are generally better options for your health, especially if you\'re mindful of your weight:\n\n### Types of Chocolate to Consider\n\n1. **Dark Chocolate:**\n   - **Benefits:** Dark chocolate (70% cocoa or higher) is rich in antioxidants and has less sugar than milk chocolate. It may also have heart health benefits and can improve mood.\n   - **Serving Size:** Stick to a small piece (about 1 ounce or 28 grams) to keep calories in check.\n\n2. **Unsweetened Cocoa Powder:**\n   - **Benefits:** Unsweetened cocoa powder is a low-calorie option that can add chocolate flavor to smoothies, oatmeal, or baked goods without added sugars.\n   - **Use:** Mix it into recipes or drinks for a chocolate boost.\n\n3. **Chocolate with Nuts:**\n   - **Benefits:** Dark chocolate combined with nuts (like almonds or hazelnuts) can provide healthy fats and protein, enhancing satiety.\n   - **Serving Size:** Again, keep portions small to enjoy the benefits without overindulging.\n\n4. **Chocolate-Covered Fruits:**\n   - **Benefits:** Fruits like strawberries, bananas, or dried fruits dipped in dark chocolate can satisfy your sweet tooth and provide nutrients.\n   - **Serving Size:** Enjoy in moderation, as dried fruits can be high in sugar and calories.\n\n5. **Homemade Chocolate Treats:**\n   - **Benefits:** Making your own chocolate treats allows you to control the ingredients and sugar content. You can use dark chocolate, nuts, and natural sweeteners like honey or maple syrup.\n   - **Ideas:** Consider making energy bites or chocolate bark with nuts and dried fruits.\n\n### Types of Chocolate to Limit\n\n1. **Milk Chocolate:**\n   - Higher in sugar and lower in cocoa content, milk chocolate is less nutritious compared to dark chocolate.\n\n2. **White Chocolate:**\n   - Technically not chocolate, as it doesn\'t contain cocoa solids. It\'s primarily sugar and fat with little to no health benefits.\n\n3. **Chocolate with Added Sugars and Fillers:**\n   - Avoid chocolates that have high amounts of added sugars, artificial flavors, or unhealthy fats.\n\n### Tips for Enjoying Chocolate Mindfully\n- **Moderation:** Enjoy chocolate as an occasional treat rather than a daily indulgence.\n- **Mindful Eating:** Savor the taste and texture, taking your time to enjoy a small piece rather than mindlessly snacking.\n- **Balance:** Pair chocolate with healthier foods, like fruits or nuts, to create a more balanced snack.\n\nBy choosing higher-quality chocolate and practicing moderation, you can still enjoy this delicious treat while supporting your health and weight loss goals!','assistant',NULL),
(13,1,4,'Who are you again?','user',NULL),
(14,1,4,'I\u2019m Fit-Chef, your helpful nutritionist and chef! I\u2019m here to provide you with guidance on healthy eating, weight loss, meal planning, and cooking tips. If you have any more questions or need assistance with anything related to nutrition or food, feel free to ask!','assistant',NULL),
(15,1,4,'Can you suggest me some healthy food?','user',NULL),
(16,1,4, E'Certainly! Here\'s a list of healthy foods that are nutritious, versatile, and can help support your overall health and weight loss goals:\n\n### Healthy Food Options\n\n#### Fruits\n1. **Berries**: Blueberries, strawberries, raspberries, and blackberries are high in antioxidants and fiber.\n2. **Apples**: A great source of fiber and vitamin C; perfect as a snack.\n3. **Bananas**: Rich in potassium and make for a quick energy boost.\n4. **Citrus Fruits**: Oranges, grapefruits, and lemons are high in vitamin C and hydration.\n\n#### Vegetables\n1. **Leafy Greens**: Spinach, kale, and swiss chard are nutrient-dense and low in calories.\n2. **Cruciferous Vegetables**: Broccoli, cauliflower, and Brussels sprouts are high in fiber and vitamins.\n3. **Bell Peppers**: Rich in vitamins A and C, and add color and crunch to meals.\n4. **Carrots**: A good source of beta-carotene, fiber, and antioxidants.\n\n#### Whole Grains\n1. **Quinoa**: A complete protein and gluten-free grain that is high in fiber.\n2. **Brown Rice**: A whole grain that provides complex carbohydrates and fiber.\n3. **Oats**: Great for breakfast, oats are high in fiber and can help keep you full.\n4. **Whole Wheat Bread or Pasta**: Choose whole grain options for added nutrients and fiber.\n\n#### Lean Proteins\n1. **Chicken Breast**: A lean source of protein that is versatile for many dishes.\n2. **Fish**: Salmon, mackerel, and sardines are high in omega-3 fatty acids.\n3. **Tofu or Tempeh**: Excellent plant-based protein sources for vegetarians and vegans.\n4. **Legumes**: Lentils, chickpeas, and black beans are high in protein and fiber.\n\n#### Healthy Fats\n1. **Avocado**: Packed with healthy monounsaturated fats and fiber.\n2. **Nuts**: Almonds, walnuts, and pistachios are great sources of healthy fats and protein (watch portions due to calorie density).\n3. **Seeds**: Chia seeds, flaxseeds, and pumpkin seeds are nutrient-dense and good sources of omega-3 fatty acids.\n4. **Olive Oil**: A heart-healthy fat that can be used in cooking or as a salad dressing.\n\n#### Dairy Alternatives\n1. **Greek Yogurt**: Higher in protein than regular yogurt and can be used in smoothies or as a snack.\n2. **Almond Milk or Oat Milk**: Nutritious dairy alternatives that can be lower in calories.\n\n### Tips for Incorporating Healthy Foods\n- **Plan Your Meals:** Prepare meals in advance to include a variety of these healthy foods.\n- **Mix and Match:** Combine different food groups for balanced meals (e.g., quinoa salad with veggies and grilled chicken).\n- **Experiment with Recipes:** Try new recipes that feature these foods to keep your meals interesting and enjoyable.\n\nIncluding a variety of these foods in your diet can help you achieve your health and weight loss goals while providing essential nutrients. If you have specific dietary preferences or restrictions, feel free to let me know for more tailored suggestions!','assistant',NULL),
(32,8,4, E'Tab: Thực đơn sống qua ngày\n\nThứ Hai:\n- Sáng: sinh tố: 1 ly\n- Trưa: Bò sốt rượu vang: 500g\n- Chiều: Trứng cá muối: 50g, Cơm gà: 1 đĩa\n\nThứ Ba:\n- Sáng: Xôi gà: 100g\n- Trưa: Cơm: 100g, cá: 1 con\n- Chiều: Cơm: 100g \n, thịt bò: 50g\n\n', 'user',NULL),
(33,8,4,'Sorry, AI is temporarily unavailable.','assistant',NULL),
(38,11,4, E'Tab: Thực đơn sống qua ngày\n\nThứ Hai:\n- Sáng: sinh tố: 1 ly\n- Trưa: Bò sốt rượu vang: 500g\n- Chiều: Trứng cá muối: 50g, Cơm gà: 1 đĩa\n\nThứ Ba:\n- Sáng: Xôi gà: 100g\n- Trưa: Cơm: 100g, cá: 1 con\n- Chiều: Cơm: 100g \n, thịt bò: 50g\n\n\nHãy đánh giá thực đơn này và đưa ra đề xuất cải thiện nếu cần thiết.','user',NULL),
(39,11,4, E'Thực đơn mà bạn cung cấp có thể chứa một số thực phẩm giàu dinh dưỡng, nhưng cũng cần cải thiện để đảm bảo cân bằng dinh dưỡng và cung cấp đủ năng lượng cho cơ thể. Dưới đây là một số đánh giá và đề xuất cải thiện cho thực đơn này:\n\n### Đánh giá thực đơn\n\n1. **Thứ Hai:**\n   - **Sáng:** Sinh tố 1 ly - Tốt cho việc cung cấp vitamin, khoáng chất và chất xơ, nhưng nên bổ sung thêm các loại trái cây khác nhau để tăng cường dinh dưỡng.\n   - **Trưa:** Bò sốt rượu vang 500g - Lượng thịt này có thể quá cao, cần cân nhắc giảm xuống và thay thế bằng các nguồn protein khác như đậu, hạt hoặc cá.\n   - **Chiều:** Trứng cá muối 50g và cơm gà 1 đĩa - Trứng cá muối có thể chứa nhiều natri, nên cân nhắc ăn với lượng vừa phải. \n\n2. **Thứ Ba:**\n   - **Sáng:** Xôi gà 100g - Tốt cho bữa sáng nhưng có thể thêm rau xanh hoặc trái cây để tăng cường chất xơ.\n   - **Trưa:** Cơm 100g và cá 1 con - Cần biết rõ loại cá và cách chế biến để đảm bảo dinh dưỡng.\n   - **Chiều:** Cơm 100g và thịt bò 50g - Giống như bữa trưa, cần cân nhắc về lượng thịt.\n\n### Đề xuất cải thiện\n\n1. **Thêm rau xanh:** Cố gắng bổ sung rau xanh vào mỗi bữa ăn để cung cấp chất xơ, vitamin và khoáng chất cần thiết cho sức khỏe.\n   \n2. **Cân bằng protein:** Thay vì chỉ sử dụng thịt, hãy thử các nguồn protein từ thực vật như đậu, hạt, hoặc các loại đậu phụ. Điều này không chỉ tốt cho sức khỏe mà còn giúp đa dạng hóa thực đơn.\n\n3. **Chất béo lành mạnh:** Cân nhắc bổ sung thêm các nguồn chất béo lành mạnh như dầu ô liu, bơ, hạt chia hay hạt lanh để hỗ trợ sức khỏe tim mạch.\n\n4. **Giảm lượng muối:** Hạn chế sử dụng thực phẩm chế biến sẵn và các loại gia vị có chứa nhiều muối để bảo vệ sức khỏe tim mạch.\n\n5. **Tráng miệng và đồ uống:** Cân nhắc thêm các loại trái cây tươi làm tráng miệng và uống nước lọc hoặc trà thảo mộc thay cho đồ uống có đường.\n\n### Ví dụ thực đơn cải thiện:\n\n**Thứ Hai:**\n- Sáng: Sinh tố với chuối, spinache, và một muỗng hạt chia.\n- Trưa: Bò sốt rượu vang 250g + rau xà lách trộn.\n- Chiều: Trứng cá muối 30g + cơm gà + rau củ luộc.\n\n**Thứ Ba:**\n- Sáng: Xôi gà + thêm 1 quả trứng luộc + rau mùi.\n- Trưa: Cơm 100g + cá hồi nướng + rau cải xanh xào.\n- Chiều: Cơm 100g + thịt bò 50g + canh rau ngót.\n\nBằng cách thực hiện các cải tiến này, bạn sẽ có một chế độ ăn uống lành mạnh và cân bằng hơn.','assistant',NULL),
(40,12,4, E'Tab: Thực đơn sống qua ngày\n\nThứ Hai:\n- Sáng: sinh tố: 1 ly\n- Trưa: Bò sốt rượu vang: 500g\n- Chiều: Trứng cá muối: 50g, Cơm gà: 1 đĩa\n\nThứ Ba:\n- Sáng: Xôi gà: 100g\n- Trưa: Cơm: 100g, cá: 1 con\n- Chiều: Cơm: 100g \n, thịt bò: 50g\n\nThứ Tư:\n- Sáng: Bánh mì: 1 ổ\n- Trưa: Cơm: 1 tô, cá: 2 con\n- Chiều: Cơm: 1 tô, gà: 200g\n\n\nHãy đánh giá thực đơn này và đưa ra đề xuất cải thiện nếu cần thiết.','user',NULL),
(41,12,4, E'Thực đơn sống qua ngày mà bạn đã cung cấp có một số món ăn thú vị và đa dạng, nhưng cũng cần có những cải thiện để đảm bảo dinh dưỡng đầy đủ và cân đối hơn. Dưới đây là một số đánh giá và đề xuất:\n\n### Đánh giá:\n\n1. **Sáng**:\n   - **Thứ Hai**: Sinh tố là một lựa chọn tốt cho bữa sáng, giúp cung cấp vitamin và khoáng chất. Tuy nhiên, nên thêm một nguồn protein (như sữa chua, trứng) để tăng cường dinh dưỡng.\n   \n2. **Trưa**:\n   - **Thứ Hai**: Bò sốt rượu vang là món ăn ngon, nhưng cần chú ý đến lượng thịt đỏ. Nên kết hợp với rau củ để tăng chất xơ.\n   \n3. **Chiều**:\n   - **Thứ Hai**: Trứng cá muối là món ăn nhiều dinh dưỡng nhưng nên kết hợp với thực phẩm khác để có bữa ăn hoàn chỉnh. Cơm gà có thể là lựa chọn tốt, nhưng cần thêm rau.\n\n### Đề xuất cải thiện:\n\n1. **Bổ sung rau củ**: Mỗi bữa ăn nên có ít nhất một phần rau củ để cung cấp chất xơ, vitamin và khoáng chất.\n\n2. **Thêm nguồn protein**: Đặc biệt vào bữa sáng, hãy thêm sữa chua, trứng hoặc hạt để tăng cường protein.\n\n3. **Cân bằng khẩu phần**: Nên cân nhắc lượng thịt đỏ và thay thế bằng thịt trắng (gà, cá) hoặc các nguồn protein thực vật (đậu, hạt) nhiều hơn để giảm cholesterol.\n\n4. **Khuyến khích trái cây**: Nên thêm trái cây vào bữa sáng hoặc như một món tráng miệng để tăng cường vitamin và khoáng chất.\n\n5. **Giảm tinh bột**: Nếu có thể, hãy giảm bớt lượng cơm trong bữa ăn để không gây tăng cân mà vẫn đảm bảo năng lượng.\n\n### Ví dụ thực đơn cải thiện:\n\n**Thứ Hai**:\n- Sáng: Sinh tố (chuối, sữa chua và hạt chia)\n- Trưa: Bò sốt rượu vang (300g), rau xào\n- Chiều: Trứng cá muối, cơm gà (1 đĩa), salad rau xanh\n\n**Thứ Ba**:\n- Sáng: Xôi gà (100g) và trái cây tươi\n- Trưa: Cơm (100g), cá (1 con), rau luộc\n- Chiều: Cơm (100g), thịt bò (50g), canh rau\n\n**Thứ Tư**:\n- Sáng: Bánh mì nguyên cám với trứng ốp la và rau sống\n- Trưa: Cơm (1 tô), cá (2 con), rau xào\n- Chiều: Cơm (1 tô), gà (200g), salad rau củ\n\nHy vọng những gợi ý này sẽ giúp bạn có một thực đơn dinh dưỡng hơn!','assistant',NULL),
(42,13,4, E'Tab: Thực đơn giảm cân\n\nNgày 1:\n- Sáng: Trứng ốp la: 2 quả, Bánh mì: 1 ổ\n- Trưa: Cơm: 1 chén, rau xanh: 50g, thịt luộc: 100g\n- Chiều: Phở: 1 tô\n\n\nHãy đánh giá thực đơn này và đưa ra đề xuất cải thiện nếu cần thiết.','user',NULL),
(43,13,4, E'Thực đơn giảm cân bạn đưa ra có một số điểm cần xem xét để đảm bảo cân bằng dinh dưỡng và hỗ trợ quá trình giảm cân hiệu quả hơn. Dưới đây là đánh giá và đề xuất cải thiện cho thực đơn:\n\n### Đánh giá thực đơn:\n1. **Bữa sáng**: \n   - Trứng ốp la (2 quả) cung cấp protein và chất béo, nhưng việc chỉ có bánh mì (1 ổ) có thể thiếu các loại rau củ, trái cây hoặc chất xơ.\n\n2. **Bữa trưa**:\n   - Cơm (1 chén) có thể khá nhiều tinh bột nếu không có hoạt động thể chất đi kèm. Thịt luộc (100g) và rau xanh (50g) là tốt, nhưng cần thêm một số chất xơ và vitamin từ rau củ khác.\n\n3. **Bữa chiều**:\n   - Phở (1 tô) thường chứa nhiều tinh bột và có thể không phù hợp cho một bữa chiều trong một thực đơn giảm cân, đặc biệt nếu phở có nhiều thịt hoặc nước dùng béo.\n\n### Đề xuất cải thiện:\n1. **Bữa sáng**:\n   - Thay vì chỉ bánh mì, bạn có thể thêm một phần trái cây (như chuối hoặc táo) và một ít rau (như rau diếp hoặc cà chua) để tăng cường vitamin và chất xơ.\n\n2. **Bữa trưa**:\n   - Giảm lượng cơm xuống còn 1/2 chén và thay thế bằng một loại rau củ khác (như bí ngòi, cà rốt, hoặc bông cải) để tăng cường chất xơ và vitamin.\n\n3. **Bữa chiều**:\n   - Thay vì phở, hãy thử một bát súp rau hoặc salad với protein (như thịt gà nướng hoặc đậu hũ) để cung cấp nhiều vitamin và chất xơ mà không quá nhiều tinh bột.\n\n### Kết luận:\nCải thiện thực đơn của bạn bằng cách thêm rau củ và trái cây, giảm lượng tinh bột, và chú ý đến chất béo lành mạnh sẽ giúp bạn có một chế độ ăn uống cân bằng hơn và hỗ trợ quá trình giảm cân hiệu quả hơn.','assistant',NULL),
(44,14,4, E'Chào bạn! Nếu bạn đang tìm kiếm một món ăn giảm cân với chế độ ăn ít carbohydrate (Low Carb), mình có thể giới thiệu cho bạn món "Salad gà nướng với sốt dầu ô liu và chanh". Đây là một món ăn đơn giản, dễ làm và rất ngon miệng!\n\n### Nguyên liệu:\n- 200g ức gà (nạc)\n- 2-3 chén rau xanh (rau xà lách, rau chân vịt, hoặc bất kỳ loại rau nào bạn thích)\n- 1 quả bơ (để bổ sung chất béo lành mạnh)\n- 1 quả cà chua (cắt lát)\n- 1/2 củ hành tây (cắt mỏng)\n- 1/4 chén hạt hạnh nhân hoặc hạt điều (tùy chọn)\n- Dầu ô liu\n- Nước cốt chanh\n- Muối, tiêu, và gia vị theo ý thích (như tỏi bột, ớt bột)\n\n### Cách làm:\n1. **Chuẩn bị ức gà**: \n   - Rửa sạch ức gà, ướp với muối, tiêu và một ít dầu ô liu. Bạn cũng có thể thêm các gia vị khác như tỏi bột hoặc ớt bột để tăng hương vị.\n   - Nướng gà ở nhiệt độ 180 độ C khoảng 20-25 phút hoặc cho đến khi gà chín và có màu vàng đẹp.\n\n2. **Chuẩn bị salad**:\n   - Trong một tô lớn, cho rau xanh, cà chua, hành tây và bơ đã cắt lát vào.\n   - Nếu bạn thích, có thể thêm hạt hạnh nhân hoặc hạt điều để tạo độ giòn cho món salad.\n\n3. **Làm sốt**:\n   - Trong một bát nhỏ, trộn đều dầu ô liu, nước cốt chanh, muối và tiêu. Bạn có thể thêm một chút mật ong nếu thích vị ngọt tự nhiên.\n\n4. **Kết hợp**:\n   - Khi gà đã chín, cắt thành miếng vừa ăn và cho lên trên salad.\n   - Rưới sốt dầu ô liu và chanh lên trên salad, trộn đều và thưởng thức!\n\n### Lợi ích:\n- Món salad này giàu protein từ gà, chất béo lành mạnh từ bơ và dầu ô liu, cùng với vitamin và khoáng chất từ rau củ.\n- Giúp bạn cảm thấy no lâu mà không cung cấp nhiều carbohydrate, rất phù hợp cho chế độ ăn kiêng giảm cân.\n\nChúc bạn thực hiện thành công và có một bữa ăn ngon miệng!','assistant',NULL),
(52,16,4,'What is this and how do I make it?','user','["uploads\\1771786273077-21353-italian-spaghetti-sauce-with-meatballs-DDMFS-4x3-a9a1528b4f06483dbec38d0c2945c378.jpg"]'),
(53,16,4, E'This dish is spaghetti and meatballs, a classic Italian-American meal. Here\'s how to make it:\n\n### Ingredients\n\n**For the Meatballs:**\n- 1 pound ground beef (or a mix of beef and pork)\n- 1/2 cup breadcrumbs\n- 1/4 cup grated Parmesan cheese\n- 1/4 cup chopped parsley\n- 1 egg\n- 2 cloves garlic, minced\n- Salt and pepper to taste\n\n**For the Sauce:**\n- 1 can (28 oz) crushed tomatoes\n- 3 cloves garlic, minced\n- 1 onion, chopped\n- 1 teaspoon dried oregano\n- 1 teaspoon dried basil\n- Salt and pepper to taste\n- Olive oil\n\n**For the Pasta:**\n- 12 ounces spaghetti\n- Grated Parmesan cheese for serving\n\n### Instructions\n\n**1. Make the Meatballs:**\n   - In a bowl, combine ground beef, breadcrumbs, Parmesan, parsley, egg, minced garlic, salt, and pepper. Mix until just combined.\n   - Form the mixture into meatballs, about 1-2 inches in diameter.\n\n**2. Cook the Meatballs:**\n   - Heat olive oil in a large skillet over medium heat. Add the meatballs and cook until browned on all sides (about 8-10 minutes). Remove and set aside.\n\n**3. Prepare the Sauce:**\n   - In the same skillet, add a bit more olive oil if needed, then sauté chopped onion and garlic until softened (about 5 minutes).\n   - Add crushed tomatoes, oregano, basil, salt, and pepper. Bring to a simmer.\n   - Return the meatballs to the skillet, cover, and let simmer for about 20-30 minutes.\n\n**4. Cook the Pasta:**\n   - While the sauce is simmering, cook the spaghetti according to package instructions in salted water. Drain.\n\n**5. Serve:**\n   - Plate the spaghetti topped with the meatballs and sauce. Sprinkle with additional Parmesan cheese and enjoy!\n\n### Tips\n- You can add red pepper flakes for some heat.\n- Fresh herbs can enhance flavor if available.\n- Serve with garlic bread or a side salad for a complete meal. \n\nEnjoy your spaghetti and meatballs!','assistant',NULL),
(54,17,4, E'Tôi có: trứng, cà chua, hành tây, cơm nguội\nMục tiêu: Giảm cân (Low Carb)','user','["uploads\\1771786556552-1712293349_compositioncompostmaderottenfood.jpg"]'),
(55,17,4, E'Với nguyên liệu bạn có (trứng, cà chua, hành tây, cơm nguội) và mục tiêu giảm cân (Low Carb), bạn có thể làm món trứng chiên cà chua và hành tây. Đây là một công thức đơn giản, ít carb và rất ngon miệng.\n\n### Nguyên liệu:\n- 2-3 quả trứng\n- 1 quả cà chua (cắt nhỏ)\n- 1/2 củ hành tây (cắt mỏng)\n- Một chút muối và tiêu\n- Dầu ô liu hoặc dầu ăn (ít)\n\n### Cách làm:\n1. **Chuẩn bị nguyên liệu**: Cắt nhỏ cà chua và hành tây.\n2. **Xào hành tây**: Trong chảo, cho một ít dầu vào, sau đó cho hành tây vào xào cho đến khi mềm và trong.\n3. **Thêm cà chua**: Cho cà chua vào chảo, nấu đến khi cà chua mềm và nước trong cà chua tiết ra.\n4. **Đánh trứng**: Trong một bát, đánh tan trứng với một chút muối và tiêu.\n5. **Đổ trứng vào chảo**: Khi cà chua và hành tây đã chín, đổ hỗn hợp trứng lên trên. Để lửa nhỏ và nấu cho đến khi trứng chín.\n6. **Hoàn thành**: Có thể gập đôi trứng hoặc để nguyên. Dùng nóng.\n\n### Mẹo:\n- Bạn có thể thêm một số gia vị như húng quế hoặc tiêu để tăng hương vị.\n- Nếu muốn bổ sung thêm rau, bạn có thể thêm rau lá xanh như cải bó xôi hoặc rau mồng tơi.\n\nChúc bạn ngon miệng và đạt được mục tiêu giảm cân!','assistant',NULL),
(56,18,4,'Tôi có: trứng, cà chua, hành tây, cơm nguội','user',NULL),
(57,18,4, E'Chào bạn! Với các nguyên liệu bạn có là trứng, cà chua, hành tây và cơm nguội, bạn có thể chế biến một món ăn ngon và bổ dưỡng. Dưới đây là công thức cho món cơm chiên trứng cà chua:\n\n### Cơm Chiên Trứng Cà Chua\n\n#### Nguyên liệu:\n- 2-3 quả trứng\n- 1-2 quả cà chua\n- 1/2 củ hành tây\n- 2 chén cơm nguội\n- Dầu ăn\n- Muối, tiêu, gia vị (tuỳ thích)\n- Hành lá (nếu có, để trang trí)\n\n#### Cách làm:\n1. **Chuẩn bị nguyên liệu:**\n   - Cà chua rửa sạch, cắt nhỏ hoặc thái hạt lựu.\n   - Hành tây bóc vỏ, cắt nhỏ.\n   - Trứng đập vào bát, đánh tan.\n\n2. **Chiên hành tây:**\n   - Đun nóng chảo với một ít dầu ăn. \n   - Cho hành tây vào xào cho thơm.\n\n3. **Thêm cà chua:**\n   - Khi hành tây đã trở nên mềm, thêm cà chua vào xào cho đến khi cà chua mềm và tiết ra nước.\n\n4. **Cho cơm nguội:**\n   - Thêm cơm nguội vào chảo, trộn đều với hành tây và cà chua. Chiên cho đến khi cơm nóng và hơi vàng.\n\n5. **Thêm trứng:**\n   - Đẩy cơm sang một bên chảo, đổ trứng vào chỗ trống. Khuấy đều trứng cho chín rồi trộn tất cả nguyên liệu lại với nhau.\n\n6. **Nêm nếm:**\n   - Nêm muối, tiêu và các gia vị khác theo khẩu vị của bạn. Xào thêm 1-2 phút cho mọi thứ hòa quyện.\n\n7. **Hoàn thành:**\n   - Tắt bếp, cho cơm ra đĩa. Có thể trang trí với hành lá cắt nhỏ nếu có.\n\n### Thưởng thức:\nMón cơm chiên trứng cà chua này rất dễ làm và thơm ngon. Bạn có thể thưởng thức nó như một bữa ăn chính hoặc ăn kèm với dưa leo hoặc rau sống.\n\nChúc bạn thành công và ngon miệng!','assistant',NULL),
(58,19,4, E'Nấu ăn từ các nguyên liệu thừa là một cách tuyệt vời để giảm lãng phí thực phẩm và sáng tạo trong bếp. Dưới đây là một số ý tưởng để bạn tận dụng các nguyên liệu thừa:\n\n### 1. **Nước dùng từ rau củ thừa**\n   - **Nguyên liệu:** Vỏ hành, cuống rau, các loại rau củ không còn tươi.\n   - **Cách làm:** Cho tất cả vào nồi, thêm nước và đun trong khoảng 30-60 phút. Lọc lấy nước dùng, có thể dùng cho súp hoặc nấu cơm.\n\n### 2. **Rau củ xào**\n   - **Nguyên liệu:** Các loại rau củ thừa như cà rốt, ớt chuông, bí.\n   - **Cách làm:** Cắt nhỏ và xào với tỏi, dầu ô liu, thêm gia vị theo sở thích.\n\n### 3. **Cháo hoặc súp từ cơm thừa**\n   - **Nguyên liệu:** Cơm nguội, rau củ thừa.\n   - **Cách làm:** Nấu cơm với nước hoặc nước dùng cho đến khi mềm, thêm rau củ và gia vị.\n\n### 4. **Smoothie từ trái cây thừa**\n   - **Nguyên liệu:** Trái cây chín (chuối, táo, dứa).\n   - **Cách làm:** Cho tất cả vào máy xay, thêm sữa hoặc nước, xay nhuyễn.\n\n### 5. **Bánh ngọt từ bột thừa**\n   - **Nguyên liệu:** Bột mì, trứng, các loại nguyên liệu còn lại.\n   - **Cách làm:** Trộn bột với đường, trứng và các nguyên liệu khác để làm bánh.\n\n### 6. **Salad từ rau củ thừa**\n   - **Nguyên liệu:** Các loại rau sống và thừa như xà lách, cà chua.\n   - **Cách làm:** Trộn các loại rau với dầu giấm, gia vị.\n\nHãy thử sáng tạo với những nguyên liệu mà bạn có, và đừng ngần ngại kết hợp các hương vị khác nhau!','assistant',NULL),
(60,21,4, E'Chào bạn! Trứng là một thực phẩm rất tốt cho sức khỏe, đặc biệt là khi bạn đang trong chế độ ăn giảm cân. Trứng giàu protein, vitamin và khoáng chất, đồng thời chứa nhiều chất dinh dưỡng cần thiết mà vẫn ít calo. Chúng cũng giúp bạn cảm thấy no lâu hơn, điều này rất hữu ích cho việc kiểm soát cân nặng.\n\nDưới đây là một gợi ý món ăn low carb với trứng:\n\n### Món: Trứng chiên với rau củ và phô mai\n\n**Nguyên liệu:**\n- 2 quả trứng\n- 1/2 quả ớt chuông (có thể chọn màu bạn thích)\n- 1/2 củ hành tây nhỏ\n- Một ít rau chân vịt (hoặc rau cải)\n- 30g phô mai (phô mai cheddar hoặc mozzarella)\n- Muối, tiêu, và một ít dầu ô liu hoặc bơ để chiên\n\n**Cách làm:**\n1. Rửa sạch và thái nhỏ ớt chuông, hành tây và rau chân vịt.\n2. Đun nóng chảo với một ít dầu ô liu hoặc bơ.\n3. Thêm hành tây và ớt chuông vào chảo, xào cho đến khi mềm.\n4. Thêm rau chân vịt vào và tiếp tục xào cho đến khi rau chín.\n5. Trong một bát, đánh tan trứng với một chút muối và tiêu.\n6. Đổ hỗn hợp trứng vào chảo và khuấy đều để trứng được phân bố đều với rau củ.\n7. Khi trứng gần chín, thêm phô mai lên trên và đậy nắp lại cho phô mai tan chảy.\n8. Khi trứng chín tới, bạn có thể cho ra đĩa và thưởng thức.\n\nMón ăn này không chỉ bổ dưỡng mà còn rất ngon miệng và ít carb, phù hợp cho chế độ ăn kiêng của bạn. Chúc bạn thành công trong hành trình giảm cân!','assistant',NULL),
(68,25,4, E'Mục tiêu: Nấu ăn từ các nguyên liệu thừa','user','["uploads\\1771820483532-1712293349_compositioncompostmaderottenfood.jpg"]'),
(69,25,4, E'Chào bạn! Với các nguyên liệu thừa trong hình, chúng ta có thể tạo ra một số món ăn ngon và sáng tạo. Dưới đây là một số ý tưởng:\n\n### Nguyên liệu:\n- Cà rốt\n- Ớt chuông đỏ\n- Ngô\n- Củ cải\n- Khoai tây\n- Gừng\n- Một số loại rau khác (có thể là hành, tỏi, hoặc các loại rau khác mà bạn có)\n\n### Món ăn đề xuất:\n\n1. **Súp rau củ**\n   - **Cách làm**: \n     1. Gọt vỏ và thái nhỏ các loại rau củ như cà rốt, khoai tây, củ cải và ớt chuông.\n     2. Nấu nước dùng (có thể dùng nước xương hoặc nước rau) và cho các loại rau vào nấu cho đến khi mềm.\n     3. Nêm nếm với muối, tiêu và một chút gừng để tăng hương vị.\n   - **Calorie**: Khoảng 150-200 calo mỗi bát, tùy thuộc vào lượng rau và cách nấu.\n\n2. **Rau củ xào**\n   - **Cách làm**: \n     1. Thái nhỏ tất cả các loại rau củ và xào với một chút dầu ăn, tỏi và gia vị.\n     2. Có thể thêm một ít nước tương hoặc dầu mè để tăng hương vị.\n   - **Calorie**: Khoảng 200-250 calo cho một phần ăn, tùy thuộc vào lượng dầu sử dụng.\n\n3. **Rau củ nướng**\n   - **Cách làm**: \n     1. Cắt rau củ thành từng miếng vừa ăn, trộn với dầu ô liu, muối và tiêu.\n     2. Nướng ở nhiệt độ 200 độ C trong khoảng 30 phút cho đến khi các loại rau chín và có màu vàng đẹp.\n   - **Calorie**: Khoảng 180-220 calo cho một phần ăn.\n\n### Mẹo:\n- Bạn có thể kết hợp nhiều loại rau củ để tạo nên nhiều hương vị khác nhau.\n- Đừng quên tận dụng cả vỏ rau củ, như vỏ khoai tây hay vỏ cà rốt, nếu chúng sạch và an toàn để ăn.\n\nHy vọng những gợi ý này sẽ giúp bạn tận dụng các nguyên liệu thừa một cách hiệu quả và thú vị! Chúc bạn nấu ăn vui vẻ! 🍽️','assistant',NULL),
(70,26,4, E'Mục tiêu: Giảm cân','user','["uploads\\1771820636178-8805-Crispy-Fried-Chicken-PICS-Beauty-4x3-240055e7b52840ff90d1c05d556db2e8.jpg"]'),
(71,26,4, E'Có vẻ như bạn đang muốn giảm cân, và hình ảnh bạn gửi cho thấy món gà rán. Món này thường chứa nhiều calo và chất béo không tốt cho việc giảm cân. Dưới đây là một số gợi ý để bạn có thể thay thế hoặc điều chỉnh chế độ ăn uống của mình:\n\n### Gợi ý món ăn thay thế:\n1. **Gà nướng**:\n   - **Nguyên liệu**: Gà (thịt ức hoặc đùi), gia vị (tỏi, tiêu, muối, chanh).\n   - **Cách làm**: Ướp gà với gia vị và nướng trên lửa vừa cho đến khi chín. Điều này sẽ giúp giảm lượng chất béo so với phương pháp rán.\n\n2. **Gà áp chảo**:\n   - **Nguyên liệu**: Gà, rau củ (bí ngòi, ớt chuông).\n   - **Cách làm**: Áp chảo gà với một ít dầu ô liu và thêm rau củ. \n\n3. **Salad gà**:\n   - **Nguyên liệu**: Gà nướng hoặc luộc, rau xanh (xà lách, cà chua, dưa chuột).\n   - **Cách làm**: Trộn tất cả nguyên liệu và thêm nước sốt nhẹ (như giấm balsamic) để tạo hương vị.\n\n### Ước lượng calo:\n- **Gà rán**: Khoảng 400-500 calo cho 100g.\n- **Gà nướng**: Khoảng 165 calo cho 100g.\n- **Salad gà**: Khoảng 250-300 calo cho một phần ăn lớn.\n\n### Lời khuyên:\n- Cố gắng hạn chế thực phẩm chiên rán và thay thế bằng các phương pháp chế biến lành mạnh hơn như nướng, hấp hoặc xào với ít dầu.\n- Thêm nhiều rau củ vào bữa ăn để cung cấp chất xơ và giúp bạn no lâu hơn.\n- Uống đủ nước và duy trì hoạt động thể chất để hỗ trợ quá trình giảm cân.\n\nNếu bạn cần thêm công thức hoặc ý tưởng cho bữa ăn khác, hãy cho tôi biết nhé!','assistant',NULL),
(72,27,4, E'Để giúp bạn duy trì năng lượng với các món ăn rẻ nhưng ngon, tôi có một vài gợi ý cho bạn:\n\n1. **Cơm chiên rau củ**:\n   - Nguyên liệu: Cơm nguội, các loại rau củ như cà rốt, đậu peas, hành tây, và trứng.\n   - Cách làm: Xào hành tây với một ít dầu ăn, sau đó thêm rau củ và cơm nguội vào xào đều. Cuối cùng cho trứng vào đảo đều. Món này dễ làm, ngon và giàu năng lượng.\n\n2. **Mì xào thịt và rau**:\n   - Nguyên liệu: Mì (có thể dùng mì gói), thịt (gà hoặc heo), và các loại rau như bông cải, cà rốt.\n   - Cách làm: Luộc mì, sau đó xào thịt với rau củ cho chín, thêm mì vào xào chung với gia vị.\n\n3. **Súp đậu lăng**:\n   - Nguyên liệu: Đậu lăng, cà rốt, hành tây, và gia vị.\n   - Cách làm: Nấu đậu lăng với nước, thêm cà rốt và hành tây vào nấu cho đến khi mềm. Món súp này vừa ấm áp lại bổ dưỡng.\n\n4. **Bánh mì kẹp với trứng và rau**:\n   - Nguyên liệu: Bánh mì, trứng, rau sống (như xà lách, cà chua).\n   - Cách làm: Chiên trứng, rồi kẹp vào bánh mì cùng với rau sống. Đây là một bữa ăn đơn giản, nhanh chóng và đầy năng lượng.\n\nTất cả những món này đều dễ làm, tiết kiệm và cung cấp năng lượng cho cơ thể bạn. Nếu bạn cần công thức chi tiết cho bất kỳ món nào, hãy cho tôi biết nhé!','assistant',NULL);

-- threads
CREATE TABLE IF NOT EXISTS threads (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  name TEXT
);

INSERT INTO threads (id, user_id, name) VALUES
(1,4,'Test Thread'),
(8,4,'AI Recommendation - Thực đơn sống qua ngày'),
(11,4,'AI Recommendation - Thực đơn sống qua ngày'),
(12,4,'AI Recommendation - Thực đơn sống qua ngày'),
(13,4,'AI Recommendation - Thực đơn giảm cân'),
(14,4,'What is this and how do I make it'),
(16,4,'Test image 2'),
(17,4,'trứng, cà chua, hành tây, cơm nguội'),
(18,4,'trứng, cà chua, hành tây, cơm nguội'),
(19,4,'Image analysis'),
(20,4,'Is this healthy?'),
(21,4,'Ăn trứng có tốt cho sức khỏe không?'),
(25,4,'Image analysis'),
(26,4,'Image analysis'),
(27,4,'Gợi ý cho tôi món ăn rẻ nhưng ngon');

-- meal_tracking
CREATE TABLE IF NOT EXISTS meal_tracking (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  date DATE NOT NULL,
  breakfast_done BOOLEAN DEFAULT FALSE,
  lunch_done BOOLEAN DEFAULT FALSE,
  dinner_done BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE(user_id, date)
);

-- user_settings
CREATE TABLE IF NOT EXISTS user_settings (
  id SERIAL PRIMARY KEY,
  user_id INTEGER UNIQUE REFERENCES users(id),
  main_tab_id INTEGER REFERENCES tabs(id)
);

INSERT INTO user_settings (id, user_id, main_tab_id) VALUES (1,4,1);

-- set sequences to match previous max ids
SELECT setval(pg_get_serial_sequence('users','id'), 6, true);
SELECT setval(pg_get_serial_sequence('tabs','id'), 3, true);
SELECT setval(pg_get_serial_sequence('blocks','id'), 8, true);
SELECT setval(pg_get_serial_sequence('threads','id'), 27, true);
SELECT setval(pg_get_serial_sequence('chats','id'), 73, true);
SELECT setval(pg_get_serial_sequence('user_settings','id'), 1, true);

COMMIT;
